// El diccionario de NucleoOS. Tres idiomas, llaves planas, y el español
// como fuente de verdad: si una llave no existe en un idioma, cae al
// español antes que mostrar un hueco. La traducción avanza módulo por
// módulo: primero la cáscara (menú, login, navegación), luego cada página.

export type Idioma = "es" | "en" | "pt";

export const IDIOMAS: Array<{ key: Idioma; label: string }> = [
  { key: "es", label: "Español" },
  { key: "en", label: "English" },
  { key: "pt", label: "Português" },
];

export const TEXTOS: Record<Idioma, Record<string, string>> = {
  es: {
    lema: "Un sistema para cambiar el rumbo de tu vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Mi vida",
    "sec.inspiracion": "Inspiración",
    "nav.inicio": "Inicio",
    "nav.calendario": "Calendario",
    "nav.revision": "Revisión",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimiento",
    "nav.vision": "Visión",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energía",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relaciones",
    "area.objetivos": "Dirección",
    "area.trabajo": "Trabajo",
    "area.finanzas": "Finanzas",
    "area.aprendizaje": "Aprendizaje",
    "topbar.menu": "Menú",
    "topbar.tema": "Cambiar tema",
    "topbar.cerrarmenu": "Cerrar menú",
    "topbar.cerrarsesion": "Cerrar sesión",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Crear cuenta",
    "login.correo": "Correo",
    "login.contrasena": "Contraseña",
    "login.minimo": "mínimo 6 caracteres",
    "login.unmomento": "Un momento…",
    "login.cuentacreada": "Cuenta creada. Revisa tu correo para confirmarla y luego entra.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "El idioma de la app. La traducción va módulo por módulo: el menú y la navegación ya cambian, el resto viene en camino.",
    cargando: "Cargando…",
    "sec.transversal": "Transversal",
    "head.sub.inicio": "Tu día de un vistazo: el pulso del cuerpo, tu brújula y tus áreas.",
    "head.sub.calendario": "Todo lo que está pasando en tu vida, en un solo lugar: pagos, citas, cumpleaños, jornadas y avances.",
    "head.sub.revision": "Lo que registras, convertido en claridad: tu día como agenda, tu semana, tu mes y los patrones entre módulos.",
    "head.sub.salud": "El combustible de tu día: sueño, agua, proteína y movimiento. Lo médico te espera en Salud clínica.",
    "head.sub.mente": "Regulación, presencia, corazón y mentalidad. Elige la vía que necesitas hoy y cuántos minutos tienes.",
    "head.sub.movimiento": "Tu cuerpo en acción: práctica suave para soltar, entrenamiento para fortalecer, y retos para sostenerlo en el tiempo.",
    "head.sub.habitos": "Sueño, ejercicio y las rutinas que construyen tu día, un check a la vez.",
    "head.sub.relaciones": "Las personas que quieres, con recordatorios amables para no perder el hilo.",
    "head.sub.objetivos": "Lo que ya decidiste: metas activas, próximos pasos y avances. La inspiración vive en Visión, aquí se mueve.",
    "head.sub.trabajo": "Tus proyectos personales, tu empleo, tus horas y cómo te sientes.",
    "head.sub.finanzas": "Gastos, presupuestos, deudas y metas de ahorro.",
    "head.sub.aprendizaje": "Tus cuadernos y notas. Lo que aprendes, guardado y buscable.",
    "head.sub.vision": "Lo que imaginas, deseas y quieres vivir. Aquí nada es obligación: cuando un sueño madura, lo conviertes en meta y pasa a Dirección.",
    "head.sub.ajustes": "Tu espacio, a tu manera.",
    "inicio.hola": "Hola",
    "tab.rev.dia": "Día",
    "tab.rev.semana": "Semana",
    "tab.rev.mes": "Mes",
    "tab.rev.patrones": "Patrones",
    "tab.sal.hoy": "Hoy",
    "tab.sal.nutricion": "Nutrición",
    "tab.sal.movimiento": "Movimiento",
    "tab.sal.sueno": "Sueño",
    "tab.sal.ciclo": "Ciclo",
    "tab.sal.recuperacion": "Recuperación",
    "tab.sal.clinica": "Salud clínica",
    "tab.vis.suenos": "Sueños",
    "tab.vis.collage": "Visual board",
    "tab.vis.ideal": "Vida ideal",
    "tab.men.practicas": "Prácticas",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Diario",
    "tab.men.historial": "Historial",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Hábitos",
    "tab.hab.retos": "Retos",
    "tab.hab.rutinas": "Rutinas",
    "tab.apr.notas": "Mis notas",
    "tab.apr.biblioteca": "Biblioteca",
    "tab.mov.suave": "Práctica suave",
    "tab.mov.entrenamiento": "Entrenamiento",
    "tab.mov.programas": "Programas",
    "tab.obj.metas": "Metas activas",
    "tab.obj.pasos": "Próximos pasos",
    "tab.obj.avances": "Avances",
    "tab.obj.logradas": "Logradas",
    "tab.fin.resumen": "Resumen",
    "tab.fin.transacciones": "Transacciones",
    "tab.fin.metas": "Metas",
    "tab.fin.deudas": "Deudas y tarjetas",
    "tab.fin.cuentas": "Cuentas",
    "tab.fin.categorias": "Categorías",
    "tab.fin.reporte": "Reporte",
    "stat.obj.activas": "Metas activas",
    "stat.obj.promedio": "Progreso promedio",
    "stat.obj.riesgo": "En riesgo",
    "stat.obj.logradas": "Logradas",
    "stat.tra.activos": "Proyectos activos",
    "stat.tra.horas7": "Horas (7 días)",
    "stat.tra.registros": "Registros",
    "stat.tra.animo": "Ánimo laboral (14 días)",
    "stat.fin.balance": "Balance en cuentas",
    "stat.fin.deuda": "Deuda total",
    "stat.fin.patrimonio": "Patrimonio neto",
    "stat.fin.ingresos": "Ingresos del mes",
    "stat.fin.gastos": "Gastos del mes",
    "btn.nuevameta": "Nueva meta",
    "btn.registraravance": "Registrar avance",
    "btn.nuevoproyecto": "Nuevo proyecto",
    "btn.registrarjornada": "Registrar jornada",
    "btn.importarcartola": "Importar cartola",
    "btn.registrar": "Registrar",
    "com.guardar": "Guardar",
    "com.guardando": "Guardando…",
    "com.cerrar": "Cerrar",
    "com.eliminar": "Eliminar",
    "com.elegir": "Elegir",
    "com.elegirfecha": "Elegir fecha",
    "com.hoy": "Hoy",
    "com.borrar": "Borrar",
    "com.hora": "hora",
    "com.min": "min",
    "com.nombre": "Nombre",
    "tp.titulo": "Elige tu tema",
    "tp.sub": "Tu espacio, tu color. Toda la app se adapta al instante.",
    "tp.listo": "Listo",
    "m.meta.que": "¿Qué quieres lograr?",
    "m.meta.area": "Área de la vida",
    "m.meta.fechaop": "Fecha límite (opcional)",
    "m.meta.fecha": "Fecha límite",
    "m.meta.alimenta": "Se alimenta de (opcional)",
    "m.meta.nada": "Nada, progreso manual o por pasos",
    "m.meta.porsemana": "Por semana",
    "m.meta.libros": "Libros en total",
    "m.meta.conectada": "Conectada a",
    "m.meta.crear": "Crear meta",
    "m.meta.editar": "Editar meta",
    "m.meta.lameta": "La meta",
    "m.meta.cambios": "Guardar cambios",
    "m.avance.que": "¿Qué lograste?",
    "m.avance.area": "Área",
    "m.avance.fecha": "Fecha",
    "m.avance.guardar": "Guardar avance",
    "m.hab.nuevo": "Nuevo hábito",
    "m.hab.editar": "Editar hábito",
    "m.hab.meta": "¿A qué meta de tu Dirección empuja? (opcional)",
    "m.tx.registrar": "Registrar movimiento",
    "m.tx.editar": "Editar movimiento",
    "m.tx.gasto": "Gasto",
    "m.tx.ingreso": "Ingreso",
    "m.tx.transfer": "Transferencia",
    "m.tx.monto": "Monto",
    "m.tx.comercio": "Comercio (a quién le pagaste)",
    "m.tx.desc": "Descripción (qué fue)",
    "m.tx.categoria": "Categoría",
    "m.tx.cuenta": "Cuenta",
    "m.gol.nueva": "Nueva meta de ahorro",
    "m.gol.editar": "Editar meta de ahorro",
    "m.gol.monto": "Monto objetivo",
    "m.gol.llevo": "Llevo ahorrado",
    "m.gol.empuja": "Empuja una meta de tu Dirección (opcional)",
    "d.titulo": "Despegue: por dónde empezar",
    "d.sub": "Lo más difícil es dejar el suelo: tus pendientes, del más liviano al más pesado. Las victorias rápidas crean el impulso.",
    "d.boton": "Despegar 🚀",
    "d.otra": "Otra pasada",
    "d.preparando": "Preparando…",
    "i.tareas": "📝 Tareas de hoy",
    "i.tareas.ph": "Hacer la cama, lavar la ropa, llamar al banco…",
    "i.tareas.anotar": "Anotar",
    "i.unpaso": "¿No sabes por dónde empezar?",
    "i.unpaso.btn": "Dime una sola cosa",
    "i.unpaso.eligiendo": "Eligiendo…",
    "i.coach": "Tu coach",
    "i.coach.ph": "Cuéntale cómo te sientes o pregúntale algo…",
    "i.coach.otro": "Otro consejo",
    "i.coach.pedir": "Pedir un consejo",
  },
  en: {
    lema: "A system to change the course of your life",
    "sec.panorama": "Overview",
    "sec.nucleo": "Core",
    "sec.mivida": "My life",
    "sec.inspiracion": "Inspiration",
    "nav.inicio": "Home",
    "nav.calendario": "Calendar",
    "nav.revision": "Review",
    "nav.mente": "Mind",
    "nav.movimiento": "Movement",
    "nav.vision": "Vision",
    "nav.ajustes": "Settings",
    "area.salud": "Energy",
    "area.habitos": "Habits",
    "area.relaciones": "Relationships",
    "area.objetivos": "Direction",
    "area.trabajo": "Work",
    "area.finanzas": "Finances",
    "area.aprendizaje": "Learning",
    "topbar.menu": "Menu",
    "topbar.tema": "Change theme",
    "topbar.cerrarmenu": "Close menu",
    "topbar.cerrarsesion": "Sign out",
    "login.entrar": "Sign in",
    "login.crearcuenta": "Create account",
    "login.correo": "Email",
    "login.contrasena": "Password",
    "login.minimo": "at least 6 characters",
    "login.unmomento": "One moment…",
    "login.cuentacreada": "Account created. Check your email to confirm it, then sign in.",
    "ajustes.idioma": "Language",
    "ajustes.idiomaDesc": "The app language. Translation is rolling out module by module: the menu and navigation already switch, the rest is on its way.",
    cargando: "Loading…",
    "sec.transversal": "Cross-cutting",
    "head.sub.inicio": "Your day at a glance: your body's pulse, your compass and your areas.",
    "head.sub.calendario": "Everything happening in your life, in one place: payments, appointments, birthdays, work days and wins.",
    "head.sub.revision": "What you log, turned into clarity: your day as an agenda, your week, your month and the patterns across modules.",
    "head.sub.salud": "Your day's fuel: sleep, water, protein and movement. The medical side lives in Clinical health.",
    "head.sub.mente": "Regulation, presence, heart and mindset. Pick the path you need today and how many minutes you have.",
    "head.sub.movimiento": "Your body in motion: gentle practice to release, training to strengthen, and challenges to keep it going.",
    "head.sub.habitos": "Sleep, exercise and the routines that build your day, one check at a time.",
    "head.sub.relaciones": "The people you love, with kind reminders so you never lose the thread.",
    "head.sub.objetivos": "What you already decided: active goals, next steps and wins. Inspiration lives in Vision, here it moves.",
    "head.sub.trabajo": "Your personal projects, your job, your hours and how you feel.",
    "head.sub.finanzas": "Spending, budgets, debts and savings goals.",
    "head.sub.aprendizaje": "Your notebooks and notes. What you learn, saved and searchable.",
    "head.sub.vision": "What you imagine, desire and want to live. Nothing here is an obligation: when a dream matures, it becomes a goal and moves to Direction.",
    "head.sub.ajustes": "Your space, your way.",
    "inicio.hola": "Hi",
    "tab.rev.dia": "Day",
    "tab.rev.semana": "Week",
    "tab.rev.mes": "Month",
    "tab.rev.patrones": "Patterns",
    "tab.sal.hoy": "Today",
    "tab.sal.nutricion": "Nutrition",
    "tab.sal.movimiento": "Movement",
    "tab.sal.sueno": "Sleep",
    "tab.sal.ciclo": "Cycle",
    "tab.sal.recuperacion": "Recovery",
    "tab.sal.clinica": "Clinical health",
    "tab.vis.suenos": "Dreams",
    "tab.vis.collage": "Vision board",
    "tab.vis.ideal": "Ideal life",
    "tab.men.practicas": "Practices",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Journal",
    "tab.men.historial": "History",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Habits",
    "tab.hab.retos": "Challenges",
    "tab.hab.rutinas": "Routines",
    "tab.apr.notas": "My notes",
    "tab.apr.biblioteca": "Library",
    "tab.mov.suave": "Gentle practice",
    "tab.mov.entrenamiento": "Training",
    "tab.mov.programas": "Programs",
    "tab.obj.metas": "Active goals",
    "tab.obj.pasos": "Next steps",
    "tab.obj.avances": "Wins",
    "tab.obj.logradas": "Achieved",
    "tab.fin.resumen": "Overview",
    "tab.fin.transacciones": "Transactions",
    "tab.fin.metas": "Goals",
    "tab.fin.deudas": "Debts and cards",
    "tab.fin.cuentas": "Accounts",
    "tab.fin.categorias": "Categories",
    "tab.fin.reporte": "Report",
    "stat.obj.activas": "Active goals",
    "stat.obj.promedio": "Average progress",
    "stat.obj.riesgo": "At risk",
    "stat.obj.logradas": "Achieved",
    "stat.tra.activos": "Active projects",
    "stat.tra.horas7": "Hours (7 days)",
    "stat.tra.registros": "Entries",
    "stat.tra.animo": "Work mood (14 days)",
    "stat.fin.balance": "Account balance",
    "stat.fin.deuda": "Total debt",
    "stat.fin.patrimonio": "Net worth",
    "stat.fin.ingresos": "Income this month",
    "stat.fin.gastos": "Spending this month",
    "btn.nuevameta": "New goal",
    "btn.registraravance": "Log a win",
    "btn.nuevoproyecto": "New project",
    "btn.registrarjornada": "Log work day",
    "btn.importarcartola": "Import statement",
    "btn.registrar": "Add",
    "com.guardar": "Save",
    "com.guardando": "Saving…",
    "com.cerrar": "Close",
    "com.eliminar": "Delete",
    "com.elegir": "Choose",
    "com.elegirfecha": "Pick a date",
    "com.hoy": "Today",
    "com.borrar": "Clear",
    "com.hora": "hour",
    "com.min": "min",
    "com.nombre": "Name",
    "tp.titulo": "Pick your theme",
    "tp.sub": "Your space, your color. The whole app adapts instantly.",
    "tp.listo": "Done",
    "m.meta.que": "What do you want to achieve?",
    "m.meta.area": "Life area",
    "m.meta.fechaop": "Deadline (optional)",
    "m.meta.fecha": "Deadline",
    "m.meta.alimenta": "Feeds on (optional)",
    "m.meta.nada": "None, manual or step-based progress",
    "m.meta.porsemana": "Per week",
    "m.meta.libros": "Books in total",
    "m.meta.conectada": "Connected to",
    "m.meta.crear": "Create goal",
    "m.meta.editar": "Edit goal",
    "m.meta.lameta": "The goal",
    "m.meta.cambios": "Save changes",
    "m.avance.que": "What did you achieve?",
    "m.avance.area": "Area",
    "m.avance.fecha": "Date",
    "m.avance.guardar": "Save win",
    "m.hab.nuevo": "New habit",
    "m.hab.editar": "Edit habit",
    "m.hab.meta": "Which Direction goal does it push? (optional)",
    "m.tx.registrar": "Add transaction",
    "m.tx.editar": "Edit transaction",
    "m.tx.gasto": "Expense",
    "m.tx.ingreso": "Income",
    "m.tx.transfer": "Transfer",
    "m.tx.monto": "Amount",
    "m.tx.comercio": "Merchant (who you paid)",
    "m.tx.desc": "Description (what it was)",
    "m.tx.categoria": "Category",
    "m.tx.cuenta": "Account",
    "m.gol.nueva": "New savings goal",
    "m.gol.editar": "Edit savings goal",
    "m.gol.monto": "Target amount",
    "m.gol.llevo": "Saved so far",
    "m.gol.empuja": "Pushes one of your Direction goals (optional)",
    "d.titulo": "Liftoff: where to start",
    "d.sub": "The hardest part is leaving the ground: your pending items, lightest to heaviest. Quick wins build momentum.",
    "d.boton": "Lift off 🚀",
    "d.otra": "Scan again",
    "d.preparando": "Preparing…",
    "i.tareas": "📝 Today's tasks",
    "i.tareas.ph": "Make the bed, do laundry, call the bank…",
    "i.tareas.anotar": "Add",
    "i.unpaso": "Not sure where to start?",
    "i.unpaso.btn": "Tell me just one thing",
    "i.unpaso.eligiendo": "Choosing…",
    "i.coach": "Your coach",
    "i.coach.ph": "Tell it how you feel or ask something…",
    "i.coach.otro": "Another tip",
    "i.coach.pedir": "Ask for a tip",
  },
  pt: {
    lema: "Um sistema para mudar o rumo da sua vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Minha vida",
    "sec.inspiracion": "Inspiração",
    "nav.inicio": "Início",
    "nav.calendario": "Calendário",
    "nav.revision": "Revisão",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimento",
    "nav.vision": "Visão",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energia",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relações",
    "area.objetivos": "Direção",
    "area.trabajo": "Trabalho",
    "area.finanzas": "Finanças",
    "area.aprendizaje": "Aprendizado",
    "topbar.menu": "Menu",
    "topbar.tema": "Mudar tema",
    "topbar.cerrarmenu": "Fechar menu",
    "topbar.cerrarsesion": "Sair",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Criar conta",
    "login.correo": "E-mail",
    "login.contrasena": "Senha",
    "login.minimo": "mínimo de 6 caracteres",
    "login.unmomento": "Um momento…",
    "login.cuentacreada": "Conta criada. Confira seu e-mail para confirmá-la e depois entre.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "O idioma do app. A tradução avança módulo por módulo: o menu e a navegação já mudam, o resto está a caminho.",
    cargando: "Carregando…",
    "sec.transversal": "Transversal",
    "head.sub.inicio": "Seu dia num relance: o pulso do corpo, sua bússola e suas áreas.",
    "head.sub.calendario": "Tudo o que está acontecendo na sua vida, num só lugar: pagamentos, consultas, aniversários, jornadas e avanços.",
    "head.sub.revision": "O que você registra, convertido em clareza: seu dia como agenda, sua semana, seu mês e os padrões entre módulos.",
    "head.sub.salud": "O combustível do seu dia: sono, água, proteína e movimento. O lado médico vive em Saúde clínica.",
    "head.sub.mente": "Regulação, presença, coração e mentalidade. Escolha o caminho que você precisa hoje e quantos minutos tem.",
    "head.sub.movimiento": "Seu corpo em ação: prática suave para soltar, treino para fortalecer e desafios para manter no tempo.",
    "head.sub.habitos": "Sono, exercício e as rotinas que constroem seu dia, um check de cada vez.",
    "head.sub.relaciones": "As pessoas que você ama, com lembretes gentis para não perder o fio.",
    "head.sub.objetivos": "O que você já decidiu: metas ativas, próximos passos e avanços. A inspiração vive em Visão, aqui ela se move.",
    "head.sub.trabajo": "Seus projetos pessoais, seu emprego, suas horas e como você se sente.",
    "head.sub.finanzas": "Gastos, orçamentos, dívidas e metas de poupança.",
    "head.sub.aprendizaje": "Seus cadernos e notas. O que você aprende, guardado e pesquisável.",
    "head.sub.vision": "O que você imagina, deseja e quer viver. Aqui nada é obrigação: quando um sonho amadurece, vira meta e passa para Direção.",
    "head.sub.ajustes": "Seu espaço, do seu jeito.",
    "inicio.hola": "Olá",
    "tab.rev.dia": "Dia",
    "tab.rev.semana": "Semana",
    "tab.rev.mes": "Mês",
    "tab.rev.patrones": "Padrões",
    "tab.sal.hoy": "Hoje",
    "tab.sal.nutricion": "Nutrição",
    "tab.sal.movimiento": "Movimento",
    "tab.sal.sueno": "Sono",
    "tab.sal.ciclo": "Ciclo",
    "tab.sal.recuperacion": "Recuperação",
    "tab.sal.clinica": "Saúde clínica",
    "tab.vis.suenos": "Sonhos",
    "tab.vis.collage": "Visual board",
    "tab.vis.ideal": "Vida ideal",
    "tab.men.practicas": "Práticas",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Diário",
    "tab.men.historial": "Histórico",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Hábitos",
    "tab.hab.retos": "Desafios",
    "tab.hab.rutinas": "Rotinas",
    "tab.apr.notas": "Minhas notas",
    "tab.apr.biblioteca": "Biblioteca",
    "tab.mov.suave": "Prática suave",
    "tab.mov.entrenamiento": "Treino",
    "tab.mov.programas": "Programas",
    "tab.obj.metas": "Metas ativas",
    "tab.obj.pasos": "Próximos passos",
    "tab.obj.avances": "Avanços",
    "tab.obj.logradas": "Alcançadas",
    "tab.fin.resumen": "Resumo",
    "tab.fin.transacciones": "Transações",
    "tab.fin.metas": "Metas",
    "tab.fin.deudas": "Dívidas e cartões",
    "tab.fin.cuentas": "Contas",
    "tab.fin.categorias": "Categorias",
    "tab.fin.reporte": "Relatório",
    "stat.obj.activas": "Metas ativas",
    "stat.obj.promedio": "Progresso médio",
    "stat.obj.riesgo": "Em risco",
    "stat.obj.logradas": "Alcançadas",
    "stat.tra.activos": "Projetos ativos",
    "stat.tra.horas7": "Horas (7 dias)",
    "stat.tra.registros": "Registros",
    "stat.tra.animo": "Ânimo no trabalho (14 dias)",
    "stat.fin.balance": "Saldo em contas",
    "stat.fin.deuda": "Dívida total",
    "stat.fin.patrimonio": "Patrimônio líquido",
    "stat.fin.ingresos": "Receitas do mês",
    "stat.fin.gastos": "Gastos do mês",
    "btn.nuevameta": "Nova meta",
    "btn.registraravance": "Registrar avanço",
    "btn.nuevoproyecto": "Novo projeto",
    "btn.registrarjornada": "Registrar jornada",
    "btn.importarcartola": "Importar extrato",
    "btn.registrar": "Registrar",
    "com.guardar": "Salvar",
    "com.guardando": "Salvando…",
    "com.cerrar": "Fechar",
    "com.eliminar": "Excluir",
    "com.elegir": "Escolher",
    "com.elegirfecha": "Escolher data",
    "com.hoy": "Hoje",
    "com.borrar": "Limpar",
    "com.hora": "hora",
    "com.min": "min",
    "com.nombre": "Nome",
    "tp.titulo": "Escolha seu tema",
    "tp.sub": "Seu espaço, sua cor. O app inteiro se adapta na hora.",
    "tp.listo": "Pronto",
    "m.meta.que": "O que você quer alcançar?",
    "m.meta.area": "Área da vida",
    "m.meta.fechaop": "Prazo (opcional)",
    "m.meta.fecha": "Prazo",
    "m.meta.alimenta": "Se alimenta de (opcional)",
    "m.meta.nada": "Nada, progresso manual ou por passos",
    "m.meta.porsemana": "Por semana",
    "m.meta.libros": "Livros no total",
    "m.meta.conectada": "Conectada a",
    "m.meta.crear": "Criar meta",
    "m.meta.editar": "Editar meta",
    "m.meta.lameta": "A meta",
    "m.meta.cambios": "Salvar mudanças",
    "m.avance.que": "O que você conquistou?",
    "m.avance.area": "Área",
    "m.avance.fecha": "Data",
    "m.avance.guardar": "Salvar avanço",
    "m.hab.nuevo": "Novo hábito",
    "m.hab.editar": "Editar hábito",
    "m.hab.meta": "Qual meta da sua Direção ele empurra? (opcional)",
    "m.tx.registrar": "Registrar movimento",
    "m.tx.editar": "Editar movimento",
    "m.tx.gasto": "Gasto",
    "m.tx.ingreso": "Receita",
    "m.tx.transfer": "Transferência",
    "m.tx.monto": "Valor",
    "m.tx.comercio": "Comércio (para quem você pagou)",
    "m.tx.desc": "Descrição (o que foi)",
    "m.tx.categoria": "Categoria",
    "m.tx.cuenta": "Conta",
    "m.gol.nueva": "Nova meta de poupança",
    "m.gol.editar": "Editar meta de poupança",
    "m.gol.monto": "Valor alvo",
    "m.gol.llevo": "Já poupei",
    "m.gol.empuja": "Empurra uma meta da sua Direção (opcional)",
    "d.titulo": "Decolagem: por onde começar",
    "d.sub": "O mais difícil é sair do chão: suas pendências, da mais leve à mais pesada. Vitórias rápidas criam o impulso.",
    "d.boton": "Decolar 🚀",
    "d.otra": "Outra rodada",
    "d.preparando": "Preparando…",
    "i.tareas": "📝 Tarefas de hoje",
    "i.tareas.ph": "Arrumar a cama, lavar a roupa, ligar para o banco…",
    "i.tareas.anotar": "Anotar",
    "i.unpaso": "Não sabe por onde começar?",
    "i.unpaso.btn": "Me diga uma coisa só",
    "i.unpaso.eligiendo": "Escolhendo…",
    "i.coach": "Seu coach",
    "i.coach.ph": "Conte como você se sente ou pergunte algo…",
    "i.coach.otro": "Outro conselho",
    "i.coach.pedir": "Pedir um conselho",
  },
};

export const CALENDARIO: Record<Idioma, { meses: string[]; dias: string[]; legible: (d: number, mes: string, y: number) => string }> = {
  es: {
    meses: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
    dias: ["lu", "ma", "mi", "ju", "vi", "sá", "do"],
    legible: (d, mes, y) => `${d} de ${mes} de ${y}`,
  },
  en: {
    meses: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    dias: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
    legible: (d, mes, y) => `${mes} ${d}, ${y}`,
  },
  pt: {
    meses: ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
    dias: ["seg", "ter", "qua", "qui", "sex", "sáb", "dom"],
    legible: (d, mes, y) => `${d} de ${mes} de ${y}`,
  },
};
