// El diccionario de NucleoOS. Tres idiomas, llaves planas, y el español
// como fuente de verdad: si una llave no existe en un idioma, cae al
// español antes que mostrar un hueco. La traducción avanza módulo por
// módulo: primero la cáscara (menú, login, navegación), luego cada página.

export type Idioma = "es" | "en" | "pt";

export const IDIOMAS: Array<{ key: Idioma; label: string }> = [
  { key: "es", label: "Español" },
  { key: "en", label: "English" },
  { key: "pt", label: "Português" },
];

export const TEXTOS: Record<Idioma, Record<string, string>> = {
  es: {
    lema: "Un sistema para cambiar el rumbo de tu vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Mi vida",
    "sec.inspiracion": "Inspiración",
    "nav.inicio": "Inicio",
    "nav.calendario": "Calendario",
    "nav.revision": "Revisión",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimiento",
    "nav.vision": "Visión",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energía",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relaciones",
    "area.objetivos": "Dirección",
    "area.trabajo": "Trabajo",
    "area.finanzas": "Finanzas",
    "area.aprendizaje": "Aprendizaje",
    "topbar.menu": "Menú",
    "topbar.tema": "Cambiar tema",
    "topbar.cerrarmenu": "Cerrar menú",
    "topbar.cerrarsesion": "Cerrar sesión",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Crear cuenta",
    "login.correo": "Correo",
    "login.contrasena": "Contraseña",
    "login.minimo": "mínimo 6 caracteres",
    "login.unmomento": "Un momento…",
    "login.cuentacreada": "Cuenta creada. Revisa tu correo para confirmarla y luego entra.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "El idioma de la app. La traducción va módulo por módulo: el menú y la navegación ya cambian, el resto viene en camino.",
    cargando: "Cargando…",
  },
  en: {
    lema: "A system to change the course of your life",
    "sec.panorama": "Overview",
    "sec.nucleo": "Core",
    "sec.mivida": "My life",
    "sec.inspiracion": "Inspiration",
    "nav.inicio": "Home",
    "nav.calendario": "Calendar",
    "nav.revision": "Review",
    "nav.mente": "Mind",
    "nav.movimiento": "Movement",
    "nav.vision": "Vision",
    "nav.ajustes": "Settings",
    "area.salud": "Energy",
    "area.habitos": "Habits",
    "area.relaciones": "Relationships",
    "area.objetivos": "Direction",
    "area.trabajo": "Work",
    "area.finanzas": "Finances",
    "area.aprendizaje": "Learning",
    "topbar.menu": "Menu",
    "topbar.tema": "Change theme",
    "topbar.cerrarmenu": "Close menu",
    "topbar.cerrarsesion": "Sign out",
    "login.entrar": "Sign in",
    "login.crearcuenta": "Create account",
    "login.correo": "Email",
    "login.contrasena": "Password",
    "login.minimo": "at least 6 characters",
    "login.unmomento": "One moment…",
    "login.cuentacreada": "Account created. Check your email to confirm it, then sign in.",
    "ajustes.idioma": "Language",
    "ajustes.idiomaDesc": "The app language. Translation is rolling out module by module: the menu and navigation already switch, the rest is on its way.",
    cargando: "Loading…",
  },
  pt: {
    lema: "Um sistema para mudar o rumo da sua vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Minha vida",
    "sec.inspiracion": "Inspiração",
    "nav.inicio": "Início",
    "nav.calendario": "Calendário",
    "nav.revision": "Revisão",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimento",
    "nav.vision": "Visão",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energia",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relações",
    "area.objetivos": "Direção",
    "area.trabajo": "Trabalho",
    "area.finanzas": "Finanças",
    "area.aprendizaje": "Aprendizado",
    "topbar.menu": "Menu",
    "topbar.tema": "Mudar tema",
    "topbar.cerrarmenu": "Fechar menu",
    "topbar.cerrarsesion": "Sair",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Criar conta",
    "login.correo": "E-mail",
    "login.contrasena": "Senha",
    "login.minimo": "mínimo de 6 caracteres",
    "login.unmomento": "Um momento…",
    "login.cuentacreada": "Conta criada. Confira seu e-mail para confirmá-la e depois entre.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "O idioma do app. A tradução avança módulo por módulo: o menu e a navegação já mudam, o resto está a caminho.",
    cargando: "Carregando…",
  },
};
