// El diccionario de NucleoOS. Tres idiomas, llaves planas, y el español
// como fuente de verdad: si una llave no existe en un idioma, cae al
// español antes que mostrar un hueco. La traducción avanza módulo por
// módulo: primero la cáscara (menú, login, navegación), luego cada página.

export type Idioma = "es" | "en" | "pt";

export const IDIOMAS: Array<{ key: Idioma; label: string }> = [
  { key: "es", label: "Español" },
  { key: "en", label: "English" },
  { key: "pt", label: "Português" },
];

export const TEXTOS: Record<Idioma, Record<string, string>> = {
  es: {
    lema: "Un sistema para cambiar el rumbo de tu vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Mi vida",
    "sec.inspiracion": "Inspiración",
    "nav.inicio": "Inicio",
    "nav.calendario": "Calendario",
    "nav.revision": "Revisión",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimiento",
    "nav.vision": "Visión",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energía",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relaciones",
    "area.objetivos": "Dirección",
    "area.trabajo": "Trabajo",
    "area.finanzas": "Finanzas",
    "area.aprendizaje": "Aprendizaje",
    "topbar.menu": "Menú",
    "topbar.tema": "Cambiar tema",
    "topbar.cerrarmenu": "Cerrar menú",
    "topbar.cerrarsesion": "Cerrar sesión",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Crear cuenta",
    "login.correo": "Correo",
    "login.contrasena": "Contraseña",
    "login.minimo": "mínimo 6 caracteres",
    "login.unmomento": "Un momento…",
    "login.cuentacreada": "Cuenta creada. Revisa tu correo para confirmarla y luego entra.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "El idioma de la app. La traducción va módulo por módulo: el menú y la navegación ya cambian, el resto viene en camino.",
    cargando: "Cargando…",
    "sec.transversal": "Transversal",
    "head.sub.inicio": "Tu día de un vistazo: el pulso del cuerpo, tu brújula y tus áreas.",
    "head.sub.calendario": "Todo lo que está pasando en tu vida, en un solo lugar: pagos, citas, cumpleaños, jornadas y avances.",
    "head.sub.revision": "Lo que registras, convertido en claridad: tu día como agenda, tu semana, tu mes y los patrones entre módulos.",
    "head.sub.salud": "El combustible de tu día: sueño, agua, proteína y movimiento. Lo médico te espera en Salud clínica.",
    "head.sub.mente": "Regulación, presencia, corazón y mentalidad. Elige la vía que necesitas hoy y cuántos minutos tienes.",
    "head.sub.movimiento": "Tu cuerpo en acción: práctica suave para soltar, entrenamiento para fortalecer, y retos para sostenerlo en el tiempo.",
    "head.sub.habitos": "Sueño, ejercicio y las rutinas que construyen tu día, un check a la vez.",
    "head.sub.relaciones": "Las personas que quieres, con recordatorios amables para no perder el hilo.",
    "head.sub.objetivos": "Lo que ya decidiste: metas activas, próximos pasos y avances. La inspiración vive en Visión, aquí se mueve.",
    "head.sub.trabajo": "Tus proyectos personales, tu empleo, tus horas y cómo te sientes.",
    "head.sub.finanzas": "Gastos, presupuestos, deudas y metas de ahorro.",
    "head.sub.aprendizaje": "Tus cuadernos y notas. Lo que aprendes, guardado y buscable.",
    "head.sub.vision": "Lo que imaginas, deseas y quieres vivir. Aquí nada es obligación: cuando un sueño madura, lo conviertes en meta y pasa a Dirección.",
    "head.sub.ajustes": "Tu espacio, a tu manera.",
    "inicio.hola": "Hola",
    "tab.rev.dia": "Día",
    "tab.rev.semana": "Semana",
    "tab.rev.mes": "Mes",
    "tab.rev.patrones": "Patrones",
    "tab.sal.hoy": "Hoy",
    "tab.sal.nutricion": "Nutrición",
    "tab.sal.movimiento": "Movimiento",
    "tab.sal.sueno": "Sueño",
    "tab.sal.ciclo": "Ciclo",
    "tab.sal.recuperacion": "Recuperación",
    "tab.sal.clinica": "Salud clínica",
    "tab.vis.suenos": "Sueños",
    "tab.vis.collage": "Visual board",
    "tab.vis.ideal": "Vida ideal",
    "tab.men.practicas": "Prácticas",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Diario",
    "tab.men.historial": "Historial",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Hábitos",
    "tab.hab.retos": "Retos",
    "tab.hab.rutinas": "Rutinas",
    "tab.apr.notas": "Mis notas",
    "tab.apr.biblioteca": "Biblioteca",
    "tab.mov.suave": "Práctica suave",
    "tab.mov.entrenamiento": "Entrenamiento",
    "tab.mov.programas": "Programas",
    "tab.obj.metas": "Metas activas",
    "tab.obj.pasos": "Próximos pasos",
    "tab.obj.avances": "Avances",
    "tab.obj.logradas": "Logradas",
    "tab.fin.resumen": "Resumen",
    "tab.fin.transacciones": "Transacciones",
    "tab.fin.metas": "Metas",
    "tab.fin.deudas": "Deudas y tarjetas",
    "tab.fin.cuentas": "Cuentas",
    "tab.fin.categorias": "Categorías",
    "tab.fin.reporte": "Reporte",
    "stat.obj.activas": "Metas activas",
    "stat.obj.promedio": "Progreso promedio",
    "stat.obj.riesgo": "En riesgo",
    "stat.obj.logradas": "Logradas",
    "stat.tra.activos": "Proyectos activos",
    "stat.tra.horas7": "Horas (7 días)",
    "stat.tra.registros": "Registros",
    "stat.tra.animo": "Ánimo laboral (14 días)",
    "stat.fin.balance": "Balance en cuentas",
    "stat.fin.deuda": "Deuda total",
    "stat.fin.patrimonio": "Patrimonio neto",
    "stat.fin.ingresos": "Ingresos del mes",
    "stat.fin.gastos": "Gastos del mes",
    "btn.nuevameta": "Nueva meta",
    "btn.registraravance": "Registrar avance",
    "btn.nuevoproyecto": "Nuevo proyecto",
    "btn.registrarjornada": "Registrar jornada",
    "btn.importarcartola": "Importar cartola",
    "btn.registrar": "Registrar",
    "agua.hint": "Toca un vaso para registrar. La meta son 8 vasos, unos dos litros.",
    "agua.nota": "El agua vive aquí, independiente de tus retos. Eso sí, si tienes un reto de agua activo, al llegar a los 8 vasos se marca solo. 💧",
    "com.guardar": "Guardar",
    "com.guardando": "Guardando…",
    "com.cerrar": "Cerrar",
    "com.eliminar": "Eliminar",
    "com.elegir": "Elegir",
    "com.elegirfecha": "Elegir fecha",
    "com.hoy": "Hoy",
    "com.borrar": "Borrar",
    "com.hora": "hora",
    "com.min": "min",
    "com.nombre": "Nombre",
    "tp.titulo": "Elige tu tema",
    "tp.sub": "Tu espacio, tu color. Toda la app se adapta al instante.",
    "tp.listo": "Listo",
    "m.meta.que": "¿Qué quieres lograr?",
    "m.meta.area": "Área de la vida",
    "m.meta.fechaop": "Fecha límite (opcional)",
    "m.meta.fecha": "Fecha límite",
    "m.meta.alimenta": "Se alimenta de (opcional)",
    "m.meta.nada": "Nada, progreso manual o por pasos",
    "m.meta.porsemana": "Por semana",
    "m.meta.libros": "Libros en total",
    "m.meta.conectada": "Conectada a",
    "m.meta.crear": "Crear meta",
    "m.meta.editar": "Editar meta",
    "m.meta.lameta": "La meta",
    "m.meta.cambios": "Guardar cambios",
    "m.avance.que": "¿Qué lograste?",
    "m.avance.area": "Área",
    "m.avance.fecha": "Fecha",
    "m.avance.guardar": "Guardar avance",
    "m.hab.nuevo": "Nuevo hábito",
    "m.hab.editar": "Editar hábito",
    "m.hab.meta": "¿A qué meta de tu Dirección empuja? (opcional)",
    "m.tx.registrar": "Registrar movimiento",
    "m.tx.editar": "Editar movimiento",
    "m.tx.gasto": "Gasto",
    "m.tx.ingreso": "Ingreso",
    "m.tx.transfer": "Transferencia",
    "m.tx.monto": "Monto",
    "m.tx.comercio": "Comercio (a quién le pagaste)",
    "m.tx.desc": "Descripción (qué fue)",
    "m.tx.categoria": "Categoría",
    "m.tx.cuenta": "Cuenta",
    "m.gol.nueva": "Nueva meta de ahorro",
    "m.gol.editar": "Editar meta de ahorro",
    "m.gol.monto": "Monto objetivo",
    "m.gol.llevo": "Llevo ahorrado",
    "m.gol.empuja": "Empuja una meta de tu Dirección (opcional)",
    "d.titulo": "Despegue: por dónde empezar",
    "d.sub": "Lo más difícil es dejar el suelo: tus pendientes, del más liviano al más pesado. Las victorias rápidas crean el impulso.",
    "d.boton": "Despegar 🚀",
    "d.otra": "Otra pasada",
    "d.preparando": "Preparando…",
    "i.tareas": "📝 Tareas de hoy",
    "i.tareas.ph": "Hacer la cama, lavar la ropa, llamar al banco…",
    "i.tareas.anotar": "Anotar",
    "i.unpaso": "¿No sabes por dónde empezar?",
    "i.unpaso.btn": "Dime una sola cosa",
    "i.unpaso.eligiendo": "Eligiendo…",
    "i.coach": "Tu coach",
    "i.coach.ph": "Cuéntale cómo te sientes o pregúntale algo…",
    "i.coach.otro": "Otro consejo",
    "i.coach.pedir": "Pedir un consejo",
  },
  en: {
    lema: "A system to change the course of your life",
    "sec.panorama": "Overview",
    "sec.nucleo": "Core",
    "sec.mivida": "My life",
    "sec.inspiracion": "Inspiration",
    "nav.inicio": "Home",
    "nav.calendario": "Calendar",
    "nav.revision": "Review",
    "nav.mente": "Mind",
    "nav.movimiento": "Movement",
    "nav.vision": "Vision",
    "nav.ajustes": "Settings",
    "area.salud": "Energy",
    "area.habitos": "Habits",
    "area.relaciones": "Relationships",
    "area.objetivos": "Direction",
    "area.trabajo": "Work",
    "area.finanzas": "Finances",
    "area.aprendizaje": "Learning",
    "topbar.menu": "Menu",
    "topbar.tema": "Change theme",
    "topbar.cerrarmenu": "Close menu",
    "topbar.cerrarsesion": "Sign out",
    "login.entrar": "Sign in",
    "login.crearcuenta": "Create account",
    "login.correo": "Email",
    "login.contrasena": "Password",
    "login.minimo": "at least 6 characters",
    "login.unmomento": "One moment…",
    "login.cuentacreada": "Account created. Check your email to confirm it, then sign in.",
    "ajustes.idioma": "Language",
    "ajustes.idiomaDesc": "The app language. Translation is rolling out module by module: the menu and navigation already switch, the rest is on its way.",
    cargando: "Loading…",
    "sec.transversal": "Cross-cutting",
    "head.sub.inicio": "Your day at a glance: your body's pulse, your compass and your areas.",
    "head.sub.calendario": "Everything happening in your life, in one place: payments, appointments, birthdays, work days and wins.",
    "head.sub.revision": "What you log, turned into clarity: your day as an agenda, your week, your month and the patterns across modules.",
    "head.sub.salud": "Your day's fuel: sleep, water, protein and movement. The medical side lives in Clinical health.",
    "head.sub.mente": "Regulation, presence, heart and mindset. Pick the path you need today and how many minutes you have.",
    "head.sub.movimiento": "Your body in motion: gentle practice to release, training to strengthen, and challenges to keep it going.",
    "head.sub.habitos": "Sleep, exercise and the routines that build your day, one check at a time.",
    "head.sub.relaciones": "The people you love, with kind reminders so you never lose the thread.",
    "head.sub.objetivos": "What you already decided: active goals, next steps and wins. Inspiration lives in Vision, here it moves.",
    "head.sub.trabajo": "Your personal projects, your job, your hours and how you feel.",
    "head.sub.finanzas": "Spending, budgets, debts and savings goals.",
    "head.sub.aprendizaje": "Your notebooks and notes. What you learn, saved and searchable.",
    "head.sub.vision": "What you imagine, desire and want to live. Nothing here is an obligation: when a dream matures, it becomes a goal and moves to Direction.",
    "head.sub.ajustes": "Your space, your way.",
    "inicio.hola": "Hi",
    "tab.rev.dia": "Day",
    "tab.rev.semana": "Week",
    "tab.rev.mes": "Month",
    "tab.rev.patrones": "Patterns",
    "tab.sal.hoy": "Today",
    "tab.sal.nutricion": "Nutrition",
    "tab.sal.movimiento": "Movement",
    "tab.sal.sueno": "Sleep",
    "tab.sal.ciclo": "Cycle",
    "tab.sal.recuperacion": "Recovery",
    "tab.sal.clinica": "Clinical health",
    "tab.vis.suenos": "Dreams",
    "tab.vis.collage": "Vision board",
    "tab.vis.ideal": "Ideal life",
    "tab.men.practicas": "Practices",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Journal",
    "tab.men.historial": "History",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Habits",
    "tab.hab.retos": "Challenges",
    "tab.hab.rutinas": "Routines",
    "tab.apr.notas": "My notes",
    "tab.apr.biblioteca": "Library",
    "tab.mov.suave": "Gentle practice",
    "tab.mov.entrenamiento": "Training",
    "tab.mov.programas": "Programs",
    "tab.obj.metas": "Active goals",
    "tab.obj.pasos": "Next steps",
    "tab.obj.avances": "Wins",
    "tab.obj.logradas": "Achieved",
    "tab.fin.resumen": "Overview",
    "tab.fin.transacciones": "Transactions",
    "tab.fin.metas": "Goals",
    "tab.fin.deudas": "Debts and cards",
    "tab.fin.cuentas": "Accounts",
    "tab.fin.categorias": "Categories",
    "tab.fin.reporte": "Report",
    "stat.obj.activas": "Active goals",
    "stat.obj.promedio": "Average progress",
    "stat.obj.riesgo": "At risk",
    "stat.obj.logradas": "Achieved",
    "stat.tra.activos": "Active projects",
    "stat.tra.horas7": "Hours (7 days)",
    "stat.tra.registros": "Entries",
    "stat.tra.animo": "Work mood (14 days)",
    "stat.fin.balance": "Account balance",
    "stat.fin.deuda": "Total debt",
    "stat.fin.patrimonio": "Net worth",
    "stat.fin.ingresos": "Income this month",
    "stat.fin.gastos": "Spending this month",
    "btn.nuevameta": "New goal",
    "btn.registraravance": "Log a win",
    "btn.nuevoproyecto": "New project",
    "btn.registrarjornada": "Log work day",
    "btn.importarcartola": "Import statement",
    "btn.registrar": "Add",
    "agua.hint": "Tap a glass to log it. The goal is 8 glasses, about two liters.",
    "agua.nota": "Water lives here, independent of your challenges. That said, if you have an active water challenge, reaching 8 glasses checks it automatically. 💧",
    "abrir": "open",
    "Mente": "Mind",
    "Energía": "Energy",
    "Sueño y movimiento": "Sleep and movement",
    "Hábitos y retos": "Habits and challenges",
    "Tareas del día": "Tasks of the day",
    "Foco": "Focus",
    "Finanzas": "Finances",
    "Dirección y avances": "Direction and wins",
    "Comidas": "Meals",
    "Movimiento": "Movement",
    "Relaciones": "Relationships",
    "Sesiones": "Sessions",
    "Minutos de práctica": "Practice minutes",
    "Sadhanas": "Sadhanas",
    "Entradas de diario": "Journal entries",
    "Agua promedio": "Average water",
    "Proteína promedio": "Average protein",
    "Energía percibida": "Perceived energy",
    "Platos registrados": "Meals logged",
    "Sueño promedio": "Average sleep",
    "Noches registradas": "Nights logged",
    "Hábitos marcados": "Habits checked",
    "Días de reto cumplidos": "Challenge days done",
    "Completadas": "Completed",
    "Bloques de foco": "Focus blocks",
    "Minutos enfocada": "Focused minutes",
    "Gastos": "Spending",
    "Ingresos": "Income",
    "Ahorro": "Savings",
    "Avances registrados": "Wins logged",
    "De aprendizaje": "From learning",
    "Conexiones con personas": "Connections with people",
    "💧 Agua": "💧 Water",
    "🍗 Proteína": "🍗 Protein",
    "⚡ ¿Cómo está tu energía?": "⚡ How is your energy?",
    "😴 Sueño de anoche": "😴 Last night's sleep",
    "🏃 Movimiento de hoy": "🏃 Today's movement",
    "📸 Tu plato": "📸 Your plate",
    "Fotografía tu comida o escríbela, y te estimo calorías, proteína, carbohidratos y grasas. Es una guía, no una balanza.": "Snap a photo of your food or type it, and I will estimate calories, protein, carbs and fat. It is a guide, not a scale.",
    "Tomar foto del plato": "Take a photo of the plate",
    "Analizando…": "Analyzing…",
    "Subir foto": "Upload photo",
    "Estimar": "Estimate",
    "Me acosté a las": "I went to bed at",
    "Desperté a las": "I woke up at",
    "Agotada": "Drained",
    "Baja": "Low",
    "Normal": "Normal",
    "Con pilas": "Energized",
    "A tope": "On fire",
    "Ordena las tarjetas a tu gusto: pasa el mouse por una y arrastra desde el agarre ⋮ de la esquina.": "Arrange the cards your way: hover over one and drag from the ⋮ handle in the corner.",
    "Tus áreas": "Your areas",
    "Avances recientes": "Recent wins",
    "1 cita próxima": "1 upcoming appointment",
    "citas próximas": "upcoming appointments",
    "por reconectar": "to reconnect",
    "🍬 Menú de dopamina": "🍬 Dopamine menu",
    "¿El cerebro pide estímulo? Elige de tu menú, no del scroll.": "Brain craving stimulation? Pick from your menu, not the scroll.",
    "Muéstrame otras": "Show me others",
    "Enfoque": "Focus",
    "Respiro": "Breather",
    "¿En qué te enfocas ahora?": "What are you focusing on now?",
    "Bloque libre, sin proyecto": "Free block, no project",
    "📚 Aprendizaje": "📚 Learning",
    "Empezar": "Start",
    "Seguir": "Resume",
    "Pausa": "Pause",
    "Minutos de foco": "Focus minutes",
    "Bloque completo. Respira, te lo ganaste. 🌱": "Block complete. Breathe, you earned it. 🌱",
    "Un bloque corto ya es empezar. Sin presión.": "A short block already counts as starting. No pressure.",
    "Toma un vaso de agua, ahora mismo.": "Drink a glass of water, right now.",
    "Párate y estira los brazos 30 segundos.": "Stand up and stretch your arms for 30 seconds.",
    "Tres respiraciones lentas, con los ojos cerrados.": "Three slow breaths, eyes closed.",
    "Abre la ventana y mira algo lejano un momento.": "Open the window and look at something far away for a moment.",
    "Ordena UNA sola cosa que tengas a la vista.": "Tidy up just ONE thing in sight.",
    "Hecho. Eso ya cuenta. 🌱": "Done. That already counts. 🌱",
    "La hice ✓": "Did it ✓",
    "Otra cosa": "Something else",
    "Dale un bloque de foco": "Give it a focus block",
    "¿Y ahora qué?": "What now?",
    "En camino": "On track",
    "En riesgo": "At risk",
    "Lograda": "Achieved",
    "En pausa": "Paused",
    "sin eventos este mes": "no events this month",
    "1 evento": "1 event",
    "eventos": "events",
    "Menstrual": "Menstrual",
    "Folicular": "Follicular",
    "Ovulatoria": "Ovulatory",
    "Lútea": "Luteal",
    "Estrógeno y progesterona en el piso: la energía baja y el cuerpo pide descanso de verdad. No es flojera, es fisiología.": "Estrogen and progesterone at their lowest: energy drops and the body asks for real rest. It is not laziness, it is physiology.",
    "El estrógeno sube y con él la energía, el ánimo y la claridad mental. Suele ser la mejor fase para empezar cosas.": "Estrogen rises and with it energy, mood and mental clarity. Usually the best phase to start things.",
    "El punto más alto de energía y sociabilidad del ciclo. El estrógeno llega a su cima.": "The highest point of energy and sociability in the cycle. Estrogen reaches its peak.",
    "La progesterona domina y hacia el final puede venir el SPM: más sensibilidad, menos paciencia, antojo de calma. Con TDAH esta fase puede sentirse más intensa.": "Progesterone takes over and PMS may arrive near the end: more sensitivity, less patience, craving calm. With ADHD this phase can feel more intense.",
    "Regálate calor (guatero, té), comida rica en hierro, planes suaves y cero exigencia. Bajar el ritmo estos días es cuidarte, no fallar.": "Gift yourself warmth (hot water bottle, tea), iron-rich food, gentle plans and zero demands. Slowing down these days is self-care, not failure.",
    "Súbete a la ola: es tu mejor fase para empezar proyectos, planificar y darle a los entrenamientos exigentes.": "Ride the wave: your best phase to start projects, plan and go for demanding workouts.",
    "Aprovecha tu cima: conversaciones importantes, panoramas con gente que quieres, movimiento. Estos días todo te fluye más fácil.": "Make the most of your peak: important conversations, plans with people you love, movement. These days everything flows easier.",
    "Baja las exigencias sociales, prioriza la comodidad y prepárate algo rico. Sentir más fuerte estos días no es exagerar, es tu química.": "Lower social demands, prioritize comfort and make yourself something nice. Feeling things more strongly these days is not overreacting, it is your chemistry.",
    "com.guardar": "Save",
    "com.guardando": "Saving…",
    "com.cerrar": "Close",
    "com.eliminar": "Delete",
    "com.elegir": "Choose",
    "com.elegirfecha": "Pick a date",
    "com.hoy": "Today",
    "com.borrar": "Clear",
    "com.hora": "hour",
    "com.min": "min",
    "com.nombre": "Name",
    "tp.titulo": "Pick your theme",
    "tp.sub": "Your space, your color. The whole app adapts instantly.",
    "tp.listo": "Done",
    "m.meta.que": "What do you want to achieve?",
    "m.meta.area": "Life area",
    "m.meta.fechaop": "Deadline (optional)",
    "m.meta.fecha": "Deadline",
    "m.meta.alimenta": "Feeds on (optional)",
    "m.meta.nada": "None, manual or step-based progress",
    "m.meta.porsemana": "Per week",
    "m.meta.libros": "Books in total",
    "m.meta.conectada": "Connected to",
    "m.meta.crear": "Create goal",
    "m.meta.editar": "Edit goal",
    "m.meta.lameta": "The goal",
    "m.meta.cambios": "Save changes",
    "m.avance.que": "What did you achieve?",
    "m.avance.area": "Area",
    "m.avance.fecha": "Date",
    "m.avance.guardar": "Save win",
    "m.hab.nuevo": "New habit",
    "m.hab.editar": "Edit habit",
    "m.hab.meta": "Which Direction goal does it push? (optional)",
    "m.tx.registrar": "Add transaction",
    "m.tx.editar": "Edit transaction",
    "m.tx.gasto": "Expense",
    "m.tx.ingreso": "Income",
    "m.tx.transfer": "Transfer",
    "m.tx.monto": "Amount",
    "m.tx.comercio": "Merchant (who you paid)",
    "m.tx.desc": "Description (what it was)",
    "m.tx.categoria": "Category",
    "m.tx.cuenta": "Account",
    "m.gol.nueva": "New savings goal",
    "m.gol.editar": "Edit savings goal",
    "m.gol.monto": "Target amount",
    "m.gol.llevo": "Saved so far",
    "m.gol.empuja": "Pushes one of your Direction goals (optional)",
    "d.titulo": "Liftoff: where to start",
    "d.sub": "The hardest part is leaving the ground: your pending items, lightest to heaviest. Quick wins build momentum.",
    "d.boton": "Lift off 🚀",
    "d.otra": "Scan again",
    "d.preparando": "Preparing…",
    "i.tareas": "📝 Today's tasks",
    "i.tareas.ph": "Make the bed, do laundry, call the bank…",
    "i.tareas.anotar": "Add",
    "i.unpaso": "Not sure where to start?",
    "i.unpaso.btn": "Tell me just one thing",
    "i.unpaso.eligiendo": "Choosing…",
    "i.coach": "Your coach",
    "i.coach.ph": "Tell it how you feel or ask something…",
    "i.coach.otro": "Another tip",
    "i.coach.pedir": "Ask for a tip",
  },
  pt: {
    lema: "Um sistema para mudar o rumo da sua vida",
    "sec.panorama": "Panorama",
    "sec.nucleo": "Núcleo",
    "sec.mivida": "Minha vida",
    "sec.inspiracion": "Inspiração",
    "nav.inicio": "Início",
    "nav.calendario": "Calendário",
    "nav.revision": "Revisão",
    "nav.mente": "Mente",
    "nav.movimiento": "Movimento",
    "nav.vision": "Visão",
    "nav.ajustes": "Ajustes",
    "area.salud": "Energia",
    "area.habitos": "Hábitos",
    "area.relaciones": "Relações",
    "area.objetivos": "Direção",
    "area.trabajo": "Trabalho",
    "area.finanzas": "Finanças",
    "area.aprendizaje": "Aprendizado",
    "topbar.menu": "Menu",
    "topbar.tema": "Mudar tema",
    "topbar.cerrarmenu": "Fechar menu",
    "topbar.cerrarsesion": "Sair",
    "login.entrar": "Entrar",
    "login.crearcuenta": "Criar conta",
    "login.correo": "E-mail",
    "login.contrasena": "Senha",
    "login.minimo": "mínimo de 6 caracteres",
    "login.unmomento": "Um momento…",
    "login.cuentacreada": "Conta criada. Confira seu e-mail para confirmá-la e depois entre.",
    "ajustes.idioma": "Idioma",
    "ajustes.idiomaDesc": "O idioma do app. A tradução avança módulo por módulo: o menu e a navegação já mudam, o resto está a caminho.",
    cargando: "Carregando…",
    "sec.transversal": "Transversal",
    "head.sub.inicio": "Seu dia num relance: o pulso do corpo, sua bússola e suas áreas.",
    "head.sub.calendario": "Tudo o que está acontecendo na sua vida, num só lugar: pagamentos, consultas, aniversários, jornadas e avanços.",
    "head.sub.revision": "O que você registra, convertido em clareza: seu dia como agenda, sua semana, seu mês e os padrões entre módulos.",
    "head.sub.salud": "O combustível do seu dia: sono, água, proteína e movimento. O lado médico vive em Saúde clínica.",
    "head.sub.mente": "Regulação, presença, coração e mentalidade. Escolha o caminho que você precisa hoje e quantos minutos tem.",
    "head.sub.movimiento": "Seu corpo em ação: prática suave para soltar, treino para fortalecer e desafios para manter no tempo.",
    "head.sub.habitos": "Sono, exercício e as rotinas que constroem seu dia, um check de cada vez.",
    "head.sub.relaciones": "As pessoas que você ama, com lembretes gentis para não perder o fio.",
    "head.sub.objetivos": "O que você já decidiu: metas ativas, próximos passos e avanços. A inspiração vive em Visão, aqui ela se move.",
    "head.sub.trabajo": "Seus projetos pessoais, seu emprego, suas horas e como você se sente.",
    "head.sub.finanzas": "Gastos, orçamentos, dívidas e metas de poupança.",
    "head.sub.aprendizaje": "Seus cadernos e notas. O que você aprende, guardado e pesquisável.",
    "head.sub.vision": "O que você imagina, deseja e quer viver. Aqui nada é obrigação: quando um sonho amadurece, vira meta e passa para Direção.",
    "head.sub.ajustes": "Seu espaço, do seu jeito.",
    "inicio.hola": "Olá",
    "tab.rev.dia": "Dia",
    "tab.rev.semana": "Semana",
    "tab.rev.mes": "Mês",
    "tab.rev.patrones": "Padrões",
    "tab.sal.hoy": "Hoje",
    "tab.sal.nutricion": "Nutrição",
    "tab.sal.movimiento": "Movimento",
    "tab.sal.sueno": "Sono",
    "tab.sal.ciclo": "Ciclo",
    "tab.sal.recuperacion": "Recuperação",
    "tab.sal.clinica": "Saúde clínica",
    "tab.vis.suenos": "Sonhos",
    "tab.vis.collage": "Visual board",
    "tab.vis.ideal": "Vida ideal",
    "tab.men.practicas": "Práticas",
    "tab.men.sadhana": "Sadhana 🕉",
    "tab.men.diario": "Diário",
    "tab.men.historial": "Histórico",
    "tab.men.insights": "Insights",
    "tab.hab.habitos": "Hábitos",
    "tab.hab.retos": "Desafios",
    "tab.hab.rutinas": "Rotinas",
    "tab.apr.notas": "Minhas notas",
    "tab.apr.biblioteca": "Biblioteca",
    "tab.mov.suave": "Prática suave",
    "tab.mov.entrenamiento": "Treino",
    "tab.mov.programas": "Programas",
    "tab.obj.metas": "Metas ativas",
    "tab.obj.pasos": "Próximos passos",
    "tab.obj.avances": "Avanços",
    "tab.obj.logradas": "Alcançadas",
    "tab.fin.resumen": "Resumo",
    "tab.fin.transacciones": "Transações",
    "tab.fin.metas": "Metas",
    "tab.fin.deudas": "Dívidas e cartões",
    "tab.fin.cuentas": "Contas",
    "tab.fin.categorias": "Categorias",
    "tab.fin.reporte": "Relatório",
    "stat.obj.activas": "Metas ativas",
    "stat.obj.promedio": "Progresso médio",
    "stat.obj.riesgo": "Em risco",
    "stat.obj.logradas": "Alcançadas",
    "stat.tra.activos": "Projetos ativos",
    "stat.tra.horas7": "Horas (7 dias)",
    "stat.tra.registros": "Registros",
    "stat.tra.animo": "Ânimo no trabalho (14 dias)",
    "stat.fin.balance": "Saldo em contas",
    "stat.fin.deuda": "Dívida total",
    "stat.fin.patrimonio": "Patrimônio líquido",
    "stat.fin.ingresos": "Receitas do mês",
    "stat.fin.gastos": "Gastos do mês",
    "btn.nuevameta": "Nova meta",
    "btn.registraravance": "Registrar avanço",
    "btn.nuevoproyecto": "Novo projeto",
    "btn.registrarjornada": "Registrar jornada",
    "btn.importarcartola": "Importar extrato",
    "btn.registrar": "Registrar",
    "agua.hint": "Toque num copo para registrar. A meta são 8 copos, uns dois litros.",
    "agua.nota": "A água vive aqui, independente dos seus desafios. Mas se você tem um desafio de água ativo, ao chegar nos 8 copos ele se marca sozinho. 💧",
    "abrir": "abrir",
    "Mente": "Mente",
    "Energía": "Energia",
    "Sueño y movimiento": "Sono e movimento",
    "Hábitos y retos": "Hábitos e desafios",
    "Tareas del día": "Tarefas do dia",
    "Foco": "Foco",
    "Finanzas": "Finanças",
    "Dirección y avances": "Direção e avanços",
    "Comidas": "Refeições",
    "Movimiento": "Movimento",
    "Relaciones": "Relações",
    "Sesiones": "Sessões",
    "Minutos de práctica": "Minutos de prática",
    "Sadhanas": "Sadhanas",
    "Entradas de diario": "Entradas de diário",
    "Agua promedio": "Água média",
    "Proteína promedio": "Proteína média",
    "Energía percibida": "Energia percebida",
    "Platos registrados": "Pratos registrados",
    "Sueño promedio": "Sono médio",
    "Noches registradas": "Noites registradas",
    "Hábitos marcados": "Hábitos marcados",
    "Días de reto cumplidos": "Dias de desafio cumpridos",
    "Completadas": "Concluídas",
    "Bloques de foco": "Blocos de foco",
    "Minutos enfocada": "Minutos focada",
    "Gastos": "Gastos",
    "Ingresos": "Receitas",
    "Ahorro": "Poupança",
    "Avances registrados": "Avanços registrados",
    "De aprendizaje": "De aprendizado",
    "Conexiones con personas": "Conexões com pessoas",
    "💧 Agua": "💧 Água",
    "🍗 Proteína": "🍗 Proteína",
    "⚡ ¿Cómo está tu energía?": "⚡ Como está sua energia?",
    "😴 Sueño de anoche": "😴 Sono de ontem",
    "🏃 Movimiento de hoy": "🏃 Movimento de hoje",
    "📸 Tu plato": "📸 Seu prato",
    "Fotografía tu comida o escríbela, y te estimo calorías, proteína, carbohidratos y grasas. Es una guía, no una balanza.": "Fotografe sua comida ou escreva, e eu estimo calorias, proteína, carboidratos e gorduras. É um guia, não uma balança.",
    "Tomar foto del plato": "Fotografar o prato",
    "Analizando…": "Analisando…",
    "Subir foto": "Enviar foto",
    "Estimar": "Estimar",
    "Me acosté a las": "Fui dormir às",
    "Desperté a las": "Acordei às",
    "Agotada": "Esgotada",
    "Baja": "Baixa",
    "Normal": "Normal",
    "Con pilas": "Com pilha",
    "A tope": "A mil",
    "Ordena las tarjetas a tu gusto: pasa el mouse por una y arrastra desde el agarre ⋮ de la esquina.": "Organize os cartões do seu jeito: passe o mouse por um e arraste pela alça ⋮ do canto.",
    "Tus áreas": "Suas áreas",
    "Avances recientes": "Avanços recentes",
    "1 cita próxima": "1 consulta próxima",
    "citas próximas": "consultas próximas",
    "por reconectar": "para reconectar",
    "🍬 Menú de dopamina": "🍬 Menu de dopamina",
    "¿El cerebro pide estímulo? Elige de tu menú, no del scroll.": "O cérebro pede estímulo? Escolha do seu menu, não do scroll.",
    "Muéstrame otras": "Me mostre outras",
    "Enfoque": "Foco",
    "Respiro": "Respiro",
    "¿En qué te enfocas ahora?": "No que você está focando agora?",
    "Bloque libre, sin proyecto": "Bloco livre, sem projeto",
    "📚 Aprendizaje": "📚 Aprendizado",
    "Empezar": "Começar",
    "Seguir": "Continuar",
    "Pausa": "Pausa",
    "Minutos de foco": "Minutos de foco",
    "Bloque completo. Respira, te lo ganaste. 🌱": "Bloco completo. Respire, você mereceu. 🌱",
    "Un bloque corto ya es empezar. Sin presión.": "Um bloco curto já é começar. Sem pressão.",
    "Toma un vaso de agua, ahora mismo.": "Beba um copo de água, agora mesmo.",
    "Párate y estira los brazos 30 segundos.": "Levante e estique os braços por 30 segundos.",
    "Tres respiraciones lentas, con los ojos cerrados.": "Três respirações lentas, de olhos fechados.",
    "Abre la ventana y mira algo lejano un momento.": "Abra a janela e olhe algo distante por um momento.",
    "Ordena UNA sola cosa que tengas a la vista.": "Organize UMA só coisa que esteja à vista.",
    "Hecho. Eso ya cuenta. 🌱": "Feito. Isso já conta. 🌱",
    "La hice ✓": "Fiz ✓",
    "Otra cosa": "Outra coisa",
    "Dale un bloque de foco": "Dê um bloco de foco",
    "¿Y ahora qué?": "E agora?",
    "En camino": "No caminho",
    "En riesgo": "Em risco",
    "Lograda": "Alcançada",
    "En pausa": "Em pausa",
    "sin eventos este mes": "sem eventos este mês",
    "1 evento": "1 evento",
    "eventos": "eventos",
    "Menstrual": "Menstrual",
    "Folicular": "Folicular",
    "Ovulatoria": "Ovulatória",
    "Lútea": "Lútea",
    "Estrógeno y progesterona en el piso: la energía baja y el cuerpo pide descanso de verdad. No es flojera, es fisiología.": "Estrogênio e progesterona no chão: a energia cai e o corpo pede descanso de verdade. Não é preguiça, é fisiologia.",
    "El estrógeno sube y con él la energía, el ánimo y la claridad mental. Suele ser la mejor fase para empezar cosas.": "O estrogênio sobe e com ele a energia, o ânimo e a clareza mental. Costuma ser a melhor fase para começar coisas.",
    "El punto más alto de energía y sociabilidad del ciclo. El estrógeno llega a su cima.": "O ponto mais alto de energia e sociabilidade do ciclo. O estrogênio chega ao topo.",
    "La progesterona domina y hacia el final puede venir el SPM: más sensibilidad, menos paciencia, antojo de calma. Con TDAH esta fase puede sentirse más intensa.": "A progesterona domina e perto do fim pode vir a TPM: mais sensibilidade, menos paciência, vontade de calma. Com TDAH esta fase pode ser mais intensa.",
    "Regálate calor (guatero, té), comida rica en hierro, planes suaves y cero exigencia. Bajar el ritmo estos días es cuidarte, no fallar.": "Presenteie-se com calor (bolsa térmica, chá), comida rica em ferro, planos leves e zero exigência. Diminuir o ritmo nesses dias é se cuidar, não falhar.",
    "Súbete a la ola: es tu mejor fase para empezar proyectos, planificar y darle a los entrenamientos exigentes.": "Surfe a onda: sua melhor fase para começar projetos, planejar e encarar treinos exigentes.",
    "Aprovecha tu cima: conversaciones importantes, panoramas con gente que quieres, movimiento. Estos días todo te fluye más fácil.": "Aproveite seu pico: conversas importantes, programas com quem você ama, movimento. Nesses dias tudo flui mais fácil.",
    "Baja las exigencias sociales, prioriza la comodidad y prepárate algo rico. Sentir más fuerte estos días no es exagerar, es tu química.": "Diminua as exigências sociais, priorize o conforto e prepare algo gostoso. Sentir mais forte nesses dias não é exagero, é sua química.",
    "com.guardar": "Salvar",
    "com.guardando": "Salvando…",
    "com.cerrar": "Fechar",
    "com.eliminar": "Excluir",
    "com.elegir": "Escolher",
    "com.elegirfecha": "Escolher data",
    "com.hoy": "Hoje",
    "com.borrar": "Limpar",
    "com.hora": "hora",
    "com.min": "min",
    "com.nombre": "Nome",
    "tp.titulo": "Escolha seu tema",
    "tp.sub": "Seu espaço, sua cor. O app inteiro se adapta na hora.",
    "tp.listo": "Pronto",
    "m.meta.que": "O que você quer alcançar?",
    "m.meta.area": "Área da vida",
    "m.meta.fechaop": "Prazo (opcional)",
    "m.meta.fecha": "Prazo",
    "m.meta.alimenta": "Se alimenta de (opcional)",
    "m.meta.nada": "Nada, progresso manual ou por passos",
    "m.meta.porsemana": "Por semana",
    "m.meta.libros": "Livros no total",
    "m.meta.conectada": "Conectada a",
    "m.meta.crear": "Criar meta",
    "m.meta.editar": "Editar meta",
    "m.meta.lameta": "A meta",
    "m.meta.cambios": "Salvar mudanças",
    "m.avance.que": "O que você conquistou?",
    "m.avance.area": "Área",
    "m.avance.fecha": "Data",
    "m.avance.guardar": "Salvar avanço",
    "m.hab.nuevo": "Novo hábito",
    "m.hab.editar": "Editar hábito",
    "m.hab.meta": "Qual meta da sua Direção ele empurra? (opcional)",
    "m.tx.registrar": "Registrar movimento",
    "m.tx.editar": "Editar movimento",
    "m.tx.gasto": "Gasto",
    "m.tx.ingreso": "Receita",
    "m.tx.transfer": "Transferência",
    "m.tx.monto": "Valor",
    "m.tx.comercio": "Comércio (para quem você pagou)",
    "m.tx.desc": "Descrição (o que foi)",
    "m.tx.categoria": "Categoria",
    "m.tx.cuenta": "Conta",
    "m.gol.nueva": "Nova meta de poupança",
    "m.gol.editar": "Editar meta de poupança",
    "m.gol.monto": "Valor alvo",
    "m.gol.llevo": "Já poupei",
    "m.gol.empuja": "Empurra uma meta da sua Direção (opcional)",
    "d.titulo": "Decolagem: por onde começar",
    "d.sub": "O mais difícil é sair do chão: suas pendências, da mais leve à mais pesada. Vitórias rápidas criam o impulso.",
    "d.boton": "Decolar 🚀",
    "d.otra": "Outra rodada",
    "d.preparando": "Preparando…",
    "i.tareas": "📝 Tarefas de hoje",
    "i.tareas.ph": "Arrumar a cama, lavar a roupa, ligar para o banco…",
    "i.tareas.anotar": "Anotar",
    "i.unpaso": "Não sabe por onde começar?",
    "i.unpaso.btn": "Me diga uma coisa só",
    "i.unpaso.eligiendo": "Escolhendo…",
    "i.coach": "Seu coach",
    "i.coach.ph": "Conte como você se sente ou pergunte algo…",
    "i.coach.otro": "Outro conselho",
    "i.coach.pedir": "Pedir um conselho",
  },
};

export const CALENDARIO: Record<Idioma, { meses: string[]; dias: string[]; legible: (d: number, mes: string, y: number) => string }> = {
  es: {
    meses: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
    dias: ["lu", "ma", "mi", "ju", "vi", "sá", "do"],
    legible: (d, mes, y) => `${d} de ${mes} de ${y}`,
  },
  en: {
    meses: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    dias: ["Mo", "Tu", "We", "Th", "Fr", "Sa", "Su"],
    legible: (d, mes, y) => `${mes} ${d}, ${y}`,
  },
  pt: {
    meses: ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
    dias: ["seg", "ter", "qua", "qui", "sex", "sáb", "dom"],
    legible: (d, mes, y) => `${d} de ${mes} de ${y}`,
  },
};
